const stations = [
  "MGR Chennai Central (MAS)",
  "Chennai Egmore (MS)",
  "Tambaram (TBM)",
  "Chengalpattu Junction (CGL)",
  "Katpadi Junction (KPD)",
  "Arakkonam Junction (AJJ)",
  "Coimbatore Junction (CBE)",
  "Salem Junction (SA)",
  "Erode Junction (ED)",
  "Tiruppur (TUP)",
  "Madurai Junction (MDU)",
  "Tirunelveli Junction (TEN)",
  "Rameswaram (RMM)",
  "Kanyakumari (CAPE)",
  "Dindigul Junction (DG)",
  "Nagercoil Junction (NCJ)",
  "Thanjavur Junction (TJ)",
  "Tiruchchirappalli Junction (TPJ)",
  "Villupuram Junction (VM)",
  "Karur Junction (KRR)",
  "Mayiladuthurai Junction (MV)",
  "Kumbakonam (KMU)",
  "Tiruvannamalai (TNM)",
  "Thiruvarur Junction (TVR)",
  "Pudukkottai (PDKT)",
  "Karaikkudi Junction (KKDI)",
  "Palani (PLNI)",
  "Sivaganga (SVGA)",
  "Paramakkudi (PMK)",
  "Manamadurai (MNM)",
  "Virudhunagar Junction (VPT)",
  "Tuticorin (TN)",
  "Kovilpatti (CVP)",
  "Tenkasi Junction (TSI)",
  "Tiruchendur (TCN)",
  "Sengottai (SCT)",
  "Ambasamudram (ASD)",
  "Cheranmahadevi (CHE)",
  "Kallidaikurichi (KIC)",
  "Sankarankovil (SNKL)",
  "Pamban (PBM)",
  "Mandapam (MMM)",
  "Perambur (PER)",
  "Perambur Carriage Works (PCW)",
  "Mambalam (MBM)",
  "Tiruvallur (TRL)",
  "Avadi (AVD)",
  "Jolarpettai Junction (JTJ)",
  "Vaniyambadi (VN)",
  "Ambur (AB)",
  "Vellore Cantt (VLR)",
  "Tirupattur (TPT)",
  "Chidambaram (CDM)",
  "Sirkazhi (SY)",
  "Karaikal (KIK)",
  "Nagappattinam (NGT)",
  "Nagore (NCR)",
  "Pattukottai (PKT)",
  "Tirutturaippundi Junction (TTP)",
  "Muthupettai (MTT)",
  "Aduthurai (ADT)",
  "Thirunageswaram (TRM)",
  "Needamangalam (NDL)",
  "Sivagangai (SVGA)",
  "Keeranur (KRUR)",
  "Golden Rock (GOC)",
  "Perambalur (PRB)",
  "Ariyalur (AAR)",
  "Jayankondam (JKM)",
  "Lalgudi (LLI)",
  "Srirangam (SRGM)",
  "Tiruchirappalli Fort (TP)",
  "Samayanallur (SYL)",
  "Sholavandan (SDN)",
  "Kodaikanal Road (KQN)",
  "Koodal Nagar (KON)",
  "Tirumangalam (TMQ)",
  "Tiruchuli (TCH)",
  "Aruppukkottai (APK)",
  "Pollachi Junction (POY)",
  "Udumalaipettai (UDT)",
  "Kinathukadavu (CNY)",
  "Mettupalayam (MTP)",
  "Ooty (UAM)",
  "Coonoor (ONR)",
  "Hillgrove (HLG)",
  "Lovedale (LOV)",
  "Fernhill (FER)",
  "Ketti (KXE)",
  "Karur (KRR)",
  "Rasipuram (RASP)",
  "Namakkal (NMKL)",
  "Salem Town (SXT)",
  "Salem Market (SAMT)",
  "Magnesite Junction (MGSJ)",
  "Omalur (OML)",
  "Mettur Dam (MTDM)",
  "Bhavani (BVR)",
  "Cuddalore Port Junction (CUPJ)",
  "Tiruppadiripuliyur (TDPR)",
  "Panruti (PRT)",
  "Vadalur (VLU)",
  "Neyveli (NVL)",
  "Tindivanam (TMV)",
  "Melmaruvathur (MLMR)",
  "Madurantakam (MMK)",
  "Singaperumalkoil (SKL)",
  "Potheri (POTI)",
  "Paranur (PRNR)",
  "Urappakkam (UPM)",
  "Vandalur (VDR)",
  "Perungalathur (PRGL)",
  "Chromepet (CMP)",
  "Pallavaram (PV)",
  "Meenambakkam (MN)",
  "Trisulam (TLM)",
  "Guindy (GDY)",
  "Saidapet (SP)",
  "St. Thomas Mount (STM)",
  "Kodambakkam (KDKM)",
  "Tiruvottiyur (TVT)",
  "Wimco Nagar (WCN)",
  "Royapuram (RPM)",
  "Washermanpet (WST)",
  "Vyasarpadi Jeeva (VJM)",
  "Korukkupet (KOK)",
  "Ennore (ENR)",
  "Minjur (MJR)",
  "Ponneri (PON)",
  "Gummidipundi (GPD)",
  "Elavur (ELR)",
  "Athipattu (ATT)",
  "Athipattu Pudhunagar (APN)",
  "Anuppambattu (APB)",
  "Nemilicherry (NEC)",
  "Thiruvalangadu (TLE)",
  "Puliyamangalam (PLMG)",
  "Manavur (MAV)",
  "Mosur (MMDA)",
  "Kadambattur (KBT)",
  "Tiruninravur (TI)",
  "Pattaravakkam (PVM)",
  "Ambattur (ABU)",
  "Korattur (KOTR)",
  "Villivakkam (VLK)",
  "Perungalathur (PRGL)",
  "Thirumayilai (MTMY)",
  "Chepauk (MCPK)",
  "Chintadripet (MCPT)",
  "Chennai Park (MPK)",
  "Chennai Fort (MSF)",
  "Chennai Beach (MSB)",
  "Basin Bridge Junction (BBQ)",
  "Kodambakkam (KDKM)",
  "Tiruttani (TRT)",
  "Ranipet (RPT)",
  "Polur (PRL)",
  "Arni Road (ARV)",
  "Vellore Cantonment (VLR)",
  "Mambalam (MBM)",
  "Perungulathur (PRGL)",
  "Samalpatti (SLY)",
  "Bhavani Sagar (BVNR)",
  "Chetpet (CPT)",
  "Uchippuli (UCP)",
  "Devakottai Road (DKO)",
  "Arantangi (ATQ)",
  "Vellore Town (VT)",
  "Alangudi (ALRU)",
  "Chettinad (CTND)",
  "Kattangulathur (CTM)",
  "Walajah Road Junction (WJR)",
  "Valadi (VLD)",
  "Pasupathikoil (PSPK)",
  "Marudai (MRDI)",
  "Perugamani (PGM)",
  "Kodai Road (KDRD)",
  "Virudhachalam Junction (VRI)",
  "Peralam Junction (PEM)",
  "Manapparai (MPA)",
  "Budalur (BAL)",
  "Tiruverumbur (TRB)",
  "Tirumanur (TIR)",
  "Annavaram (ANV)",
  "Papanasam (PML)",
  "Vadakadu (VDK)",
  "Mannargudi (MQ)",
  "Valangaiman (VGM)",
  "Koradacheri (KDC)",
  "Nidamangalam Junction (NMJ)",
  "Tiruvarur Junction (TVR)",
  "Kumbakonam (KMU)",
  "Darasuram (DSM)",
  "Kuttiadi (KTA)",
  "Kumbakonam (KMU)",
  "Mayiladuthurai Junction (MV)",
  "Sirkazhi (SY)",
  "Chidambaram (CDM)",
  "Parangipettai (PRPT)",
  "Vaithisvarankoil (VDL)",
  "Kollidam (CLM)",
  "Chozhapuram (CZM)",
  "Siruvachur (SRVR)",
  "Sendurai (SDUR)",
  "Virudhachalam Town (VDT)",
  "Pazhayapalayam (PZPM)",
  "Pachur (PCU)"
];

export default stations;
