const trains = [
  {
    number: "12710",
    name: "Nellai Express",
    from: "Erode",
    to: "Chennai Egmore",
    departure: "18:49",
    arrival: "13:25",
    days: ["Sat", "Sun"],
    coaches: { B1: 20, A1: 70 },
  },
  {
    number: "17436",
    name: "Cheran Express",
    from: "Coimbatore",
    to: "Tuticorin",
    departure: "13:34",
    arrival: "20:09",
    days: ["Mon", "Wed", "Fri"],
    coaches: { A1: 17, A2: 55, B1: 35, B2: 48 },
  },
  {
    number: "13173",
    name: "Kovai Express",
    from: "Kumbakonam",
    to: "Nagapattinam",
    departure: "18:47",
    arrival: "15:46",
    days: ["Sat", "Sun"],
    coaches: { B1: 7, SL: 71, A2: 13, A1: 50, B2: 59 },
  },
  {
    number: "18507",
    name: "Pothigai Express",
    from: "Tiruchirappalli",
    to: "Kanyakumari",
    departure: "13:55",
    arrival: "07:13",
    days: ["Tue", "Thu", "Sat"],
    coaches: { SL: 33, A1: 29, B1: 72, A2: 34 },
  },
  {
    number: "20464",
    name: "Pearl City Express",
    from: "Cuddalore",
    to: "Chennai Egmore",
    departure: "13:46",
    arrival: "22:15",
    days: ["Daily"],
    coaches: { A1: 28, B1: 58 },
  },

  // 95 more trains below (autogenerated with proper logic)
  ...Array.from({ length: 95 }, (_, i) => {
    const stations = [
      "Chennai Egmore", "Chennai Central", "Madurai", "Tirunelveli", "Coimbatore", "Rameswaram", "Kanyakumari",
      "Tiruchirappalli", "Salem", "Erode", "Thanjavur", "Dindigul", "Villupuram", "Vellore", "Nagercoil",
      "Tiruvannamalai", "Kumbakonam", "Mayiladuthurai", "Tuticorin", "Nagapattinam", "Cuddalore", "Tambaram",
      "Karur", "Namakkal", "Perambur"
    ];

    const coaches = ["SL", "B1", "B2", "A1", "A2"];
    const from = stations[Math.floor(Math.random() * stations.length)];
    let to = stations[Math.floor(Math.random() * stations.length)];
    while (to === from) to = stations[Math.floor(Math.random() * stations.length)];

    const getTime = () =>
      `${String(Math.floor(Math.random() * 24)).padStart(2, '0')}:${String(Math.floor(Math.random() * 60)).padStart(2, '0')}`;

    const coachAvailability = Object.fromEntries(
      [...Array(Math.floor(Math.random() * 4) + 2)].map(() => {
        const coach = coaches[Math.floor(Math.random() * coaches.length)];
        return [coach, Math.floor(Math.random() * 72)];
      })
    );

    return {
      number: `12${600 + i}`,
      name: `Mock Express ${i + 6}`,
      from,
      to,
      departure: getTime(),
      arrival: getTime(),
      days: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"].filter((_, d) => (i + d) % 2 === 0),
      coaches: coachAvailability
    };
  }),
];

export default trains;
